export const API_ERROR = 'API_ERROR'

export const ESH_ITEMS_RECEIVE = 'ESH_ITEMS_RECEIVE'
export const ESH_ITEM_STATE = 'ESH_ITEM_STATE'
export const ESH_ITEM_UPDATE = 'ESH_ITEM_UPDATE'
export const ESH_ITEM_ADD = 'ESH_ITEM_ADD'
export const ESH_ITEM_REMOVE = 'ESH_ITEM_REMOVE'
